#+STARTUP:indent
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/styles.css"/>
#+HTML_HEAD_EXTRA: <link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono|Ubuntu' rel='stylesheet' type='text/css'>
#+OPTIONS: f:nil author:nil num:1 creator:nil timestamp:nil 
#+TITLE: The Game of Life
#+AUTHOR: Stephen Brown

#+BEGIN_HTML
<div class=ribbon>
<a href="https://github.com/stsb11/9-CS-gameOfLife">Fork me on GitHub</a>
</div>
#+END_HTML

* COMMENT Use as a template
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:

** Research It
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:

** Design It
:PROPERTIES:
:HTML_CONTAINER_CLASS: design
:END:

** Build It
:PROPERTIES:
:HTML_CONTAINER_CLASS: build
:END:

** Test It
:PROPERTIES:
:HTML_CONTAINER_CLASS: test
:END:

** Run It
:PROPERTIES:
:HTML_CONTAINER_CLASS: run
:END:

** Document It
:PROPERTIES:
:HTML_CONTAINER_CLASS: document
:END:

** Code It
:PROPERTIES:
:HTML_CONTAINER_CLASS: code
:END:

** Program It
:PROPERTIES:
:HTML_CONTAINER_CLASS: program
:END:

** Try It
:PROPERTIES:
:HTML_CONTAINER_CLASS: try
:END:

** Badge It
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:

** Save It
:PROPERTIES:
:HTML_CONTAINER_CLASS: save
:END:

* Broom broom!
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
- Cars are one of the best ways of gobbling up your cash. The purchase price, the insurance, the tax, the MOT, the fuel and the endless repair bills quickly erode your finances. 
- You can either choose to buy a car, or to lease one - often called a PCP (personal contract plan). Leasing deals involve you paying a deposit, a fixed sum each month and (generally) a lump sum at the end if you want to keep the car.  If you don’t, most lease deals give a GMFV (‘guaranteed minimum future value’).
- Some people say “I’ll just buy a cheap car, for economical motoring”. However if a car’s cheap to buy, there’s probably a reason for it! On the other hand, if you buy an expensive one, you’ve got costly loan/lease payments every month and these can still break down.
** Try It
:PROPERTIES:
:HTML_CONTAINER_CLASS: document
:END:
- Take a look online, and find a car over at the AutoTrader website. For a first car, £2500 should buy you something that /might/ be reasonably reliable. 
  - *Tip:* Remember that a car with a big engine (> 1.3 litre engine) will go faster than a small car, but will also have a thirst for petrol and tyres to match as well as dramatically increasing your insurance costs. A bigger car will necessitate sacrificing more of your disposable income to drive to work and back. 
- Once you’ve found your dream motor, open [[www.MoneySupermarket.com][www.moneysupermarket.com]] in a new browser tab and find out the cost of insuring it on a 'fully comprehensive' basis.   
  -For the purposes of your quote, enter ‘21’ as your age; to make things simple, use the School's address. It's worth knowing that the cost of insurance varies depending on where you live.
  - *Tip:* Full comprehensive insurance means that if you crash into someone else, the insurance company will pay for yours and their car to be repaired. 
  - *Tip:* Third party, fire and theft insurance means that if you crash into someone else, the insurance company will pay for their car to be repaired. This is a cheaper option, as long as your never have an accident that is your fault. 

- As this is a big lump sum of cash to find all at once, many people will take out a loan to pay for it over a year too.
- You’ll probably want to look at a loan to pay for it over a year too; get moneysupermarket.com to give you some quotes.
- Once you’ve done this, visit the pages of one of the major car manufacturers and get a PCP quote on the cheapest model in the range.
** Document It
:PROPERTIES:
:HTML_CONTAINER_CLASS: document
:END:
- Add the monthly cost of your chosen car to the monthly outgoing form, in column =F=.
- Make a note on your spreadsheet of which option you went for (buying or leasing), and why.
** Badge It
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:
- *Silver:* Write three pieces of advice for someone considering buying their first car, and record them in the spaces provided on the spreadsheet in cells =K44=, =K45= and =K46=.
